// Code generated by go-swagger; DO NOT EDIT.

package geolocate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetGeolocateIPParams creates a new GetGeolocateIPParams object
// with the default values initialized.
func NewGetGeolocateIPParams() *GetGeolocateIPParams {
	var ()
	return &GetGeolocateIPParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGeolocateIPParamsWithTimeout creates a new GetGeolocateIPParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGeolocateIPParamsWithTimeout(timeout time.Duration) *GetGeolocateIPParams {
	var ()
	return &GetGeolocateIPParams{

		timeout: timeout,
	}
}

// NewGetGeolocateIPParamsWithContext creates a new GetGeolocateIPParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGeolocateIPParamsWithContext(ctx context.Context) *GetGeolocateIPParams {
	var ()
	return &GetGeolocateIPParams{

		Context: ctx,
	}
}

// NewGetGeolocateIPParamsWithHTTPClient creates a new GetGeolocateIPParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGeolocateIPParamsWithHTTPClient(client *http.Client) *GetGeolocateIPParams {
	var ()
	return &GetGeolocateIPParams{
		HTTPClient: client,
	}
}

/*GetGeolocateIPParams contains all the parameters to send to the API endpoint
for the get geolocate IP operation typically these are written to a http.Request
*/
type GetGeolocateIPParams struct {

	/*IP
	  valid ipv4/v6 address

	*/
	IP string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get geolocate IP params
func (o *GetGeolocateIPParams) WithTimeout(timeout time.Duration) *GetGeolocateIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get geolocate IP params
func (o *GetGeolocateIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get geolocate IP params
func (o *GetGeolocateIPParams) WithContext(ctx context.Context) *GetGeolocateIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get geolocate IP params
func (o *GetGeolocateIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get geolocate IP params
func (o *GetGeolocateIPParams) WithHTTPClient(client *http.Client) *GetGeolocateIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get geolocate IP params
func (o *GetGeolocateIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIP adds the ip to the get geolocate IP params
func (o *GetGeolocateIPParams) WithIP(ip string) *GetGeolocateIPParams {
	o.SetIP(ip)
	return o
}

// SetIP adds the ip to the get geolocate IP params
func (o *GetGeolocateIPParams) SetIP(ip string) {
	o.IP = ip
}

// WriteToRequest writes these params to a swagger request
func (o *GetGeolocateIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ip
	if err := r.SetPathParam("ip", o.IP); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
