host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for getting geolocation info
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Geolocation API
  version: "1.0"
paths:
  /geolocate/{ip}:
    get:
      consumes:
      - text/plain
      description: inquires IP geolocation's API to get details in json format
      parameters:
      - description: valid ipv4/v6 address
        in: path
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: invalid or missing ip address
          schema:
            type: string
        "500":
          description: unable to parse response from geolocation API
          schema:
            type: string
      summary: returns geolocation info given ip address
      tags:
      - geolocate
swagger: "2.0"
